version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: laravel8-php-fpm-80
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            - ./:/var/www
        networks: 
            - app-network
    
    mysql:
        image: mysql:5.7.33
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: myportfweb
            MYSQL_USER: user
        volumes: 
            - ./mysql/data:/var/lib/mysql
        networks:
            - app-network

    mysql_test:
        image: mysql:5.7.33
        container_name: mysql_test
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: myportfweb_test
            MYSQL_USER: user
        networks:
            - app-network
    
    nginx:
        image: nginx:1.19.8-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports: 
            - 8100:80
        volumes: 
            - ./:/var/www
            - ./nginx/conf:/etc/nginx/conf.d
        networks: 
            - app-network

    npm: 
        image: node:16-alpine3.14
        container_name: node
        volumes: 
            - ./:/var/www
        working_dir: /var/www
        entrypoint: ['npm']
        command: 'install'
        networks: 
            - app-network